### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range.

### ISSUE THREAD

**Issue by ylcnfrht** [socketio/socket.io-redis-adapter#384]
Hi,
I have a node js application and at this application I use socket.io-redis and today I faced with this error. Does anyone face this error before ? And If you faced how did you solved it ?

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 601. Received 602
at boundsError (internal/buffer.js:49:9)
at Buffer.readUInt8 (internal/buffer.js:213:5)
at Decoder.parse (/application/node_modules/notepack.io/lib/decode.js:86:28)
at Decoder.map (/application/node_modules/notepack.io/lib/decode.js:20:23)
at Decoder.parse (/application/node_modules/notepack.io/lib/decode.js:58:19)
at Decoder.map (/application/node_modules/notepack.io/lib/decode.js:19:16)
at Decoder.parse (/application/node_modules/notepack.io/lib/decode.js:232:19)
at Decoder.array (/application/node_modules/notepack.io/lib/decode.js:11:21)
at Decoder.parse (/application/node_modules/notepack.io/lib/decode.js:62:19)
at Decoder.map (/application/node_modules/notepack.io/lib/decode.js:20:23)
at Decoder.parse (/application/node_modules/notepack.io/lib/decode.js:58:19)
at Decoder.array (/application/node_modules/notepack.io/lib/decode.js:11:21)
at Decoder.parse (/application/node_modules/notepack.io/lib/decode.js:62:19)
at Object.decode (/application/node_modules/notepack.io/lib/decode.js:244:23)
at Redis.onmessage (/application/node_modules/socket.io-redis/index.js:148:24)
at RedisClient.emit (events.js:198:13)
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
