### ISSUE TITLE
redis 4: ERR_INVALID_ARG_TYPE The "chunk" argument must be of type string

### ISSUE THREAD

**Issue by cesco69** [socketio/socket.io-redis-adapter#439]
Error

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received type function ([Function])

at validChunk (_stream_writable.js:281:10)
at Socket.Writable.write (_stream_writable.js:316:21)
at RedisSocket.writeCommand (\node_modules\@node-redis\client\dist\lib\client\socket.js:57:130)
at Commander._RedisClient_tick (\node_modules\@node-redis\client\dist\lib\client\index.js:421:64)
at Commander._RedisClient_sendCommand (\node_modules\@node-redis\client\dist\lib\client\index.js:402:82)
at Commander.sendCommand (\node_modules\@node-redis\client\dist\lib\client\index.js:356:93)
at Commander.<computed>.<computed> (\node_modules\@node-redis\client\dist\lib\client\index.js:390:27)
at new RedisAdapter (\node_modules\@socket.io\redis-adapter\dist\index.js:75:28)
at new <anonymous> (\node_modules\@socket.io\redis-adapter\dist\index.js:45:16)
at Namespace._initAdapter (\node_modules\socket.io\dist\namespace.js:40:24)
```

**package.json**

```json
"dependencies": {
    "@socket.io/redis-adapter": "^7.1.0",
    "express": "^4.17.2",
    "express-socket.io-session": "^1.3.5",
    "redis": "^4.0.1",
    "socket.io": "^4.4.1",
    "socket.io-client": "^4.4.1",
}
```

Example of implementation

```ts
import { createAdapter } from '@socket.io/redis-adapter';
import * as redis from 'redis';
import * as SocketIO from 'socket.io';

// ...

const socketServer = new SocketIO.Server( ... );

const pubClient = redis.createClient({
    url: `redis://localhost:6379`,
    legacyMode: true,
});
const subClient = pubClient.duplicate();

await pubClient.connect();
await subClient.connect();

socketServer.adapter(createAdapter(pubClient, subClient));
```

**Comment by darrachequesne** [comment]
Hi! I think this is due to the `legacyMode`. I haven't found any workaround for now, unfortunately...

See also: https://github.com/socketio/socket.io-redis-adapter/issues/430#issuecomment-992162660

Reference: https://github.com/socketio/socket.io-redis-adapter/issues/430#issuecomment-992162660

**Comment by cesco69** [comment]
yes, with `legacyMode: false` it works!

**Comment by darrachequesne** [comment]
Good news, thanks for the update :+1:

**Comment by cesco69** [comment]
@darrachequesne the problem is here https://github.com/socketio/socket.io-redis-adapter/blob/master/lib/index.ts#L117
with `legacyMode: true` the `const isRedisV4 = typeof this.pubClient.pSubscribe === "function";` is `true`, but the redis client works like V3 API. Maybe you need to check also if legacyMode is false, eg.: `const isRedisV4 = typeof this.pubClient.pSubscribe === "function" && !legacyMode;`

**Comment by darrachequesne** [comment]
@cesco69 that's an interesting idea! Would you have time to open a pull request?
