### ISSUE TITLE
 Error('Got an unexpected reply from Redis');

### ISSUE THREAD

**Issue by dinceremre** [socketio/socket.io-redis-adapter#483]
I start to get this error this morning. no activity on redis cli MONITOR.
can you please help.

  throw new Error('Got an unexpected reply from Redis');
                    ^

Error: Got an unexpected reply from Redis
    at Object.onReply (/home/pc/HVLDialogue/DlgFeatureBranch/im-server/node_modules/@redis/client/dist/lib/client/commands-queue.js:57:27)
    at RESP2Decoder.write (/home/pc/HVLDialogue/DlgFeatureBranch/im-server/node_modules/@redis/client/dist/lib/client/RESP2/decoder.js:119:26)

"dependencies": {
    "@socket.io/redis-adapter": "^7.1.1",
    "@socket.io/redis-emitter": "^5.0.0",
    "@types/helmet": "^4.0.0",
    "@types/twig": "^1.12.9",
    "bluebird": "^3.7.2",
    "compression": "^1.7.4",
    "debug": "^4.3.4",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "helmet": "^6.0.1",
    "lodash": "^4.17.21",
    "lusca": "^1.7.0",
    "morgan": "^1.10.0",
    "path": "^0.12.7",
    "redis": "^4.0.1",
    "socket.io": "^4.5.4",
    "twig": "^1.15.4",
    "uuid-validate": "^0.0.3"
  }

**Comment by dinceremre** [comment]
redis connection string was the issue.
