### ISSUE TITLE
the below error occurs when the user disconnect from the socket 

### ISSUE THREAD

**Issue by Gandhisurya** [socketio/socket.io-redis-adapter#532]
TypeError: this.adapter.persistSession is not a function
    at Socket._onclose (/Users/gandhi/Documents/mainProjects/pepul-chat/oneapp/oneapp-chat-dev/node_modules/socket.io/dist/socket.js:551:26)
    at Client.onclose (/Users/gandhi/Documents/mainProjects/pepul-chat/oneapp/oneapp-chat-dev/node_modules/socket.io/dist/client.js:247:20)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at Socket.onClose (/Users/gandhi/Documents/mainProjects/pepul-chat/oneapp/oneapp-chat-dev/node_modules/engine.io/build/socket.js:310:18)
    at Object.onceWrapper (node:events:633:28)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.onClose (/Users/gandhi/Documents/mainProjects/pepul-chat/oneapp/oneapp-chat-dev/node_modules/engine.io/build/transport.js:110:14)
    at Object.onceWrapper (node:events:634:26)

**Comment by darrachequesne** [comment]
Unfortunately, the Connection State Recovery feature is not currently supported by this adapter.
