### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by pnodet** [socketio/socket.io-redis-adapter#539]
```diff
dependencies:
- @socket.io/redis-adapter 8.2.1
+ @socket.io/redis-adapter 8.3.0
```

```
/Users/pnodet/backend/node_modules/.pnpm/@socket.io+redis-adapter@8.3.0_socket.io-adapter@2.5.2_bufferutil@4.0.8_/node_modules/@socket.io/redis-adapter/dist/sharded-adapter.js:27
class ShardedRedisAdapter extends socket_io_adapter_1.ClusterAdapter {
                                                      ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/pnodet/backend/node_modules/.pnpm/@socket.io+redis-adapter@8.3.0_socket.io-adapter@2.5.2_bufferutil@4.0.8_/node_modules/@socket.io/redis-adapter/dist/sharded-adapter.js:27:55)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.S (/Users/pnodet/backend/node_modules/.pnpm/tsx@4.7.2/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/pnodet/backend/node_modules/.pnpm/@socket.io+redis-adapter@8.3.0_socket.io-adapter@2.5.2_bufferutil@4.0.8_/node_modules/@socket.io/redis-adapter/dist/index.js:704:25)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.S (/Users/pnodet/backend/node_modules/.pnpm/tsx@4.7.2/node_modules/tsx/dist/cjs/index.cjs:1:1292)
```

```sh
❯ node -v
v20.10.0
```

```
"@socket.io/redis-adapter": "8.3.0",
"socket.io": "4.7.5"
```

**Comment by bruceCzK** [comment]
Same here.

**Comment by darrachequesne** [comment]
What is your version of the `socket.io-adapter` package? It should be `2.5.4`, isn't that the case?

See: https://github.com/socketio/socket.io-redis-adapter/blob/cdb55353f83c78cabe9788683e4dd93ac4cd50c9/package.json#L27-L29

**Comment by pnodet** [comment]
Specifying the peerDependencies seems to solve the issue on my side, not sure why pnpm prefers installing `2.5.2` though

**Comment by bruceCzK** [comment]
Delete `yarn.lock` then `yarn install` again fix the issue.
